CREATE TABLE IF NOT EXISTS rsvp (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  cardId TEXT NOT NULL,          -- Thêm ID thiệp
  name TEXT NOT NULL,
  phone TEXT,
  isComing INTEGER NOT NULL,
  guestCount INTEGER DEFAULT 1,
  guestOf TEXT DEFAULT NULL,
  createdAt TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS messages (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  cardId TEXT NOT NULL,          -- Thêm ID thiệp
  name TEXT NOT NULL,
  message TEXT NOT NULL,
  reply TEXT,
  createdAt TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS cards (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  cardId TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  createdAt TEXT DEFAULT CURRENT_TIMESTAMP
);

